stages:
    - build
    - test
    - deploy

Buil dJob:
    stage: build
    script:
        - echo "Building Project"

Test Job:
    stage: test
    script:
        - echo "Testing"

Deploy Job:
    stage: deploy
    script:
        - echo "Deplyoing"


        