# Nginx + ACME + NextJS deployment

services:
  nextjs:
    container_name: WebApp
    build:
      args:
        - MONGODB_URL=$MONGODB_URL
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    networks:
      - proxy
    environment:
      - AUTH_SECRET=$AUTH_SECRET
      - API_KEY_LASER=$API_KEY_LASER
      - API_KEY_PRINTERS=$API_KEY_PRINTERS
      - AUTH_TRUST_HOST=$AUTH_TRUST_HOST
      - MONGODB_URL=$MONGODB_URL
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - VIRTUAL_HOST=$DOMAIN
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - LETSENCRYPT_HOST=$DOMAIN
      - AUTH_MICROSOFT_ENTRA_ID_SECRET=$AUTH_MICROSOFT_ENTRA_ID_SECRET
      - AUTH_MICROSOFT_ENTRA_ID_ISSUER=$AUTH_MICROSOFT_ENTRA_ID_ISSUER
      - AUTH_MICROSOFT_ENTRA_ID_ID=$AUTH_MICROSOFT_ENTRA_ID_ID
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.9
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
    environment:
      - VIRTUAL_HOST=$DOMAIN
    networks:
      - proxy
    restart: unless-stopped

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-acme
    volumes_from:
      - nginx-proxy:rw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=$LETSENCRYPT_EMAIL
    networks:
      - proxy

networks:
  proxy:

volumes:
  certs:
  html:
  acme:
