import Permissions from '@/database/permission.model';
import { connectToDatabase } from '@/lib/mongoose';
import { NextRequest } from 'next/server';
import { Db, GridFSBucket } from 'mongodb';

// Get all permissions
export async function GET(request: NextRequest) {
  try {
    await connectToDatabase();
    const perms = await Permissions.find({});

    return new Response(JSON.stringify(perms), { status: 200 });
  } catch (err) {
    return new Response('Failed to fetch permissions', { status: 500 });
  }
}

// Create a new permission
export async function POST(request: NextRequest) {
  try {
    await connectToDatabase();
    console.log('Hello');

    const formData = await request.json();

    // Getting all the form data , code generated by claude AI , might change later for a more compact code but works for now
    const { name, abbreviation, description, scheduling, permission, image } = formData;
    console.log(name);

    return new Response(
      JSON.stringify({
        message: 'Permission created successfully',
      }),
      { status: 201 }
    );
  } catch (err) {
    return new Response('Failed to create permission', { status: 500 });
  }
}
